name: check-indendation
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:         
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Super-Linter
        uses: github/super-linter@v7.2.0   
      - name: my-step
        run: echo "Hello world"