name: python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4.2.2

      - name: set up python
        uses: actions/setup-python@v5.3.0

      - name: Install dependencies
        run: |
          python -m install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest
    